// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentApi.Data;

#nullable disable

namespace StudentApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423200017_AddRejectionComment")]
    partial class AddRejectionComment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentApi.Models.Education", b =>
                {
                    b.Property<int>("IdEducation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEducation"));

                    b.Property<string>("DegreeOfEducation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EducationEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("EducationStartDate")
                        .HasColumnType("date");

                    b.Property<string>("EducationalInstitution")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GroupNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<string>("NameTutor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PatronymicTutor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SurnameTutor")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdEducation");

                    b.HasIndex("IdQuestionnaire");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("StudentApi.Models.PlacePractice", b =>
                {
                    b.Property<int>("IdPlacePractice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlacePractice"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<string>("MainFunctions")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PracticeEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PracticeStartDate")
                        .HasColumnType("date");

                    b.HasKey("IdPlacePractice");

                    b.HasIndex("IdQuestionnaire");

                    b.ToTable("PlacePractice");
                });

            modelBuilder.Entity("StudentApi.Models.PlaceWork", b =>
                {
                    b.Property<int>("IdPlaceWork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlaceWork"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<string>("MainFunctions")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Position")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ReasonForDismissal")
                        .HasColumnType("text");

                    b.Property<DateTime?>("WorkEndDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("WorkStartDate")
                        .HasColumnType("date");

                    b.HasKey("IdPlaceWork");

                    b.HasIndex("IdQuestionnaire");

                    b.ToTable("PlaceWork");
                });

            modelBuilder.Entity("StudentApi.Models.PracticePriority", b =>
                {
                    b.Property<int>("IdPracticePriority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPracticePriority"));

                    b.Property<int>("Estimation")
                        .HasColumnType("integer");

                    b.Property<int>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<string>("Wording")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPracticePriority");

                    b.HasIndex("IdQuestionnaire");

                    b.ToTable("PracticePriority");
                });

            modelBuilder.Entity("StudentApi.Models.PracticeReview", b =>
                {
                    b.Property<int>("IdPracticeReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPracticeReview"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ExperienceUsefulness")
                        .HasColumnType("integer");

                    b.Property<int>("IdStudentApplication")
                        .HasColumnType("integer");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<bool>("ReadyToWork")
                        .HasColumnType("boolean");

                    b.Property<int>("SpecialityRelevance")
                        .HasColumnType("integer");

                    b.Property<int>("SupervisionQuality")
                        .HasColumnType("integer");

                    b.HasKey("IdPracticeReview");

                    b.HasIndex("IdStudentApplication")
                        .IsUnique();

                    b.ToTable("PracticeReview");
                });

            modelBuilder.Entity("StudentApi.Models.PsychologicalQuestions", b =>
                {
                    b.Property<int>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineImportance")
                        .HasColumnType("text");

                    b.Property<string>("Friendliness")
                        .HasColumnType("text");

                    b.Property<string>("LateInstances")
                        .HasColumnType("text");

                    b.Property<string>("StressfulWorkReadiness")
                        .HasColumnType("text");

                    b.Property<string>("SubordinateAction")
                        .HasColumnType("text");

                    b.Property<string>("UnacceptableQualities")
                        .HasColumnType("text");

                    b.Property<string>("ValuedQualities")
                        .HasColumnType("text");

                    b.Property<string>("WorkTimeDedication")
                        .HasColumnType("text");

                    b.HasKey("IdQuestionnaire");

                    b.ToTable("PsychologicalQuestions");
                });

            modelBuilder.Entity("StudentApi.Models.Questionnaire", b =>
                {
                    b.Property<int>("IdQuestionnaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdQuestionnaire"));

                    b.Property<bool>("AdminLiability")
                        .HasColumnType("boolean");

                    b.Property<string>("Birthplace")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ChronicConditions")
                        .HasColumnType("text");

                    b.Property<string>("Citizenship")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("CriminalLiability")
                        .HasColumnType("boolean");

                    b.Property<bool>("DataProcessingConsent")
                        .HasColumnType("boolean");

                    b.Property<int>("IdStudent")
                        .HasColumnType("integer");

                    b.Property<string>("MedContraindications")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Residency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("VacationSideJob")
                        .HasColumnType("boolean");

                    b.Property<bool>("VolunteeringReadiness")
                        .HasColumnType("boolean");

                    b.HasKey("IdQuestionnaire");

                    b.HasIndex("IdStudent");

                    b.ToTable("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.Relative", b =>
                {
                    b.Property<int>("IdRelative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRelative"));

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("date");

                    b.Property<int>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PlaceStudy")
                        .HasColumnType("text");

                    b.Property<string>("PlaceWork")
                        .HasColumnType("text");

                    b.Property<string>("RelationDegree")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdRelative");

                    b.HasIndex("IdQuestionnaire");

                    b.ToTable("Relative");
                });

            modelBuilder.Entity("StudentApi.Models.Skill", b =>
                {
                    b.Property<int>("IdSkill")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSkill"));

                    b.Property<int>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdSkill");

                    b.HasIndex("IdQuestionnaire");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("StudentApi.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStudent"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("HadLamaPractice")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLamaEmployee")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdStudent");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StudentApi.Models.StudentApplication", b =>
                {
                    b.Property<int>("IdStudentApplication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStudentApplication"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdPracticeType")
                        .HasColumnType("integer");

                    b.Property<int?>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<int?>("IdScheduledPractice")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<int>("IdStudent")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionComment")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("StudentApplicationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("IdStudentApplication");

                    b.HasIndex("IdQuestionnaire");

                    b.HasIndex("IdStudent");

                    b.ToTable("StudentApplication");
                });

            modelBuilder.Entity("StudentApi.Models.StudentDocument", b =>
                {
                    b.Property<int>("IdStudentDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStudentDocument"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContractStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdDocumentType")
                        .HasColumnType("integer");

                    b.Property<int?>("IdSpecialization")
                        .HasColumnType("integer");

                    b.Property<int>("IdStudent")
                        .HasColumnType("integer");

                    b.Property<int>("IdStudentApplication")
                        .HasColumnType("integer");

                    b.Property<string>("UploadStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdStudentDocument");

                    b.HasIndex("IdStudent");

                    b.HasIndex("IdStudentApplication");

                    b.ToTable("StudentDocument");
                });

            modelBuilder.Entity("StudentApi.Models.StudentProject", b =>
                {
                    b.Property<int>("IdStudentProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdStudentProject"));

                    b.Property<DateTime?>("DateParticipation")
                        .HasColumnType("date");

                    b.Property<int>("IdQuestionnaire")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOurOrganizationEvent")
                        .HasColumnType("boolean");

                    b.Property<string>("Organizer")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdStudentProject");

                    b.HasIndex("IdQuestionnaire");

                    b.ToTable("StudentProject");
                });

            modelBuilder.Entity("StudentApi.Models.Education", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithMany("Educations")
                        .HasForeignKey("IdQuestionnaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.PlacePractice", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithMany("PlacePractices")
                        .HasForeignKey("IdQuestionnaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.PlaceWork", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithMany("PlaceWorks")
                        .HasForeignKey("IdQuestionnaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.PracticePriority", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithMany("PracticePriorities")
                        .HasForeignKey("IdQuestionnaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.PracticeReview", b =>
                {
                    b.HasOne("StudentApi.Models.StudentApplication", "StudentApplication")
                        .WithOne("PracticeReview")
                        .HasForeignKey("StudentApi.Models.PracticeReview", "IdStudentApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentApplication");
                });

            modelBuilder.Entity("StudentApi.Models.PsychologicalQuestions", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithOne("PsychologicalQuestions")
                        .HasForeignKey("StudentApi.Models.PsychologicalQuestions", "IdQuestionnaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.Questionnaire", b =>
                {
                    b.HasOne("StudentApi.Models.Student", "Student")
                        .WithMany("Questionnaires")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentApi.Models.Relative", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithMany("Relatives")
                        .HasForeignKey("IdQuestionnaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.Skill", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithMany("Skills")
                        .HasForeignKey("IdQuestionnaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.StudentApplication", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("IdQuestionnaire")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StudentApi.Models.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentApi.Models.StudentDocument", b =>
                {
                    b.HasOne("StudentApi.Models.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentApi.Models.StudentApplication", "StudentApplication")
                        .WithMany("Documents")
                        .HasForeignKey("IdStudentApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentApplication");
                });

            modelBuilder.Entity("StudentApi.Models.StudentProject", b =>
                {
                    b.HasOne("StudentApi.Models.Questionnaire", "Questionnaire")
                        .WithMany("StudentProjects")
                        .HasForeignKey("IdQuestionnaire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("StudentApi.Models.Questionnaire", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("PlacePractices");

                    b.Navigation("PlaceWorks");

                    b.Navigation("PracticePriorities");

                    b.Navigation("PsychologicalQuestions");

                    b.Navigation("Relatives");

                    b.Navigation("Skills");

                    b.Navigation("StudentProjects");
                });

            modelBuilder.Entity("StudentApi.Models.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Documents");

                    b.Navigation("Questionnaires");
                });

            modelBuilder.Entity("StudentApi.Models.StudentApplication", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("PracticeReview");
                });
#pragma warning restore 612, 618
        }
    }
}
